// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VitaliaBackend.Shared.Infrastructure.Persistence.EntityFrameworkCore.Configuration;

#nullable disable

namespace VitaliaBackend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260703123000_AddPatientEhrCode")]
    partial class AddPatientEhrCode
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("VitaliaBackend.Tenant.Domain.Model.Aggregates.Patient", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)")
                        .HasColumnName("user_id");

                    b.Property<DateTime?>("ActiveThru")
                        .HasColumnType("date")
                        .HasColumnName("active_thru");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("code");

                    b.Property<string>("EHRCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("ehr_code");

                    b.Property<string>("EmergencyContactName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("varchar(160)")
                        .HasColumnName("emergency_contact_name");

                    b.Property<string>("EmergencyContactPhone")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("emergency_contact_phone");

                    b.Property<string>("InsuranceProvider")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("insurance_provider");

                    b.Property<string>("PolicyNumber")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("policy_number");

                    b.HasKey("UserId")
                        .HasName("p_k_patients");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("i_x_patients_code");

                    b.HasIndex("EHRCode")
                        .IsUnique()
                        .HasDatabaseName("i_x_patients_e_h_r_code");

                    b.ToTable("patients", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
